import type { Course, Lesson, Word, DailyTask } from "./types";

export const courses: Course[] = [
  {
    id: "animals",
    title: "Animal Friends",
    description: "Learn the names of cute animals!",
    icon: "paw",
    color: "#82D5BB",
    totalLessons: 8,
    completedLessons: 5,
    wordCount: 40,
  },
  {
    id: "colors",
    title: "Rainbow Colors",
    description: "Discover the colors around you!",
    icon: "palette",
    color: "#F8A6B2",
    totalLessons: 6,
    completedLessons: 2,
    wordCount: 30,
  },
  {
    id: "food",
    title: "Yummy Food",
    description: "Name your favorite snacks!",
    icon: "apple",
    color: "#F7CD67",
    totalLessons: 7,
    completedLessons: 0,
    wordCount: 35,
  },
  {
    id: "nature",
    title: "Nature Walk",
    description: "Explore trees, flowers and sky!",
    icon: "leaf",
    color: "#8AC68A",
    totalLessons: 6,
    completedLessons: 0,
    wordCount: 28,
  },
];

export const lessons: Lesson[] = [
  { id: "l1", courseId: "animals", title: "Farm Animals", state: "completed", wordCount: 5, estimatedMinutes: 5 },
  { id: "l2", courseId: "animals", title: "Pet Animals", state: "completed", wordCount: 5, estimatedMinutes: 5 },
  { id: "l3", courseId: "animals", title: "Ocean Creatures", state: "completed", wordCount: 5, estimatedMinutes: 6 },
  { id: "l4", courseId: "animals", title: "Jungle Animals", state: "completed", wordCount: 5, estimatedMinutes: 6 },
  { id: "l5", courseId: "animals", title: "Birds & Insects", state: "completed", wordCount: 5, estimatedMinutes: 5 },
  { id: "l6", courseId: "animals", title: "Baby Animals", state: "available", wordCount: 5, estimatedMinutes: 5 },
  { id: "l7", courseId: "animals", title: "Animal Sounds", state: "locked", wordCount: 5, estimatedMinutes: 6 },
  { id: "l8", courseId: "animals", title: "Animal Homes", state: "locked", wordCount: 5, estimatedMinutes: 6 },
];

export const words: Word[] = [
  {
    id: "w1",
    text: "Cat",
    phonics: "/k\u00e6t/",
    meaning: "\u5c0f\u732b",
    illustration: "A fluffy orange cat sitting on a cushion",
    options: ["Cat", "Dog", "Rabbit", "Fish"],
    correctIndex: 0,
  },
  {
    id: "w2",
    text: "Dog",
    phonics: "/d\u0252\u0259/",
    meaning: "\u5c0f\u72d7",
    illustration: "A happy golden puppy wagging its tail",
    options: ["Bird", "Dog", "Horse", "Duck"],
    correctIndex: 1,
  },
  {
    id: "w3",
    text: "Fish",
    phonics: "/f\u026a\u0283/",
    meaning: "\u5c0f\u9c7c",
    illustration: "A colorful fish swimming in a bowl",
    options: ["Frog", "Crab", "Fish", "Whale"],
    correctIndex: 2,
  },
  {
    id: "w4",
    text: "Bird",
    phonics: "/b\u025c\u02d0rd/",
    meaning: "\u5c0f\u9e1f",
    illustration: "A little blue bird on a tree branch",
    options: ["Bird", "Bee", "Bat", "Ant"],
    correctIndex: 0,
  },
  {
    id: "w5",
    text: "Rabbit",
    phonics: "/\u02c8r\u00e6b\u026at/",
    meaning: "\u5154\u5b50",
    illustration: "A white rabbit eating a carrot",
    options: ["Mouse", "Hamster", "Squirrel", "Rabbit"],
    correctIndex: 3,
  },
  {
    id: "w6",
    text: "Frog",
    phonics: "/fr\u0252\u0259/",
    meaning: "\u9752\u86d9",
    illustration: "A green frog sitting on a lily pad",
    options: ["Frog", "Toad", "Snake", "Turtle"],
    correctIndex: 0,
  },
  {
    id: "w7",
    text: "Horse",
    phonics: "/h\u0254\u02d0rs/",
    meaning: "\u9a6c",
    illustration: "A brown horse running in a field",
    options: ["Cow", "Sheep", "Horse", "Goat"],
    correctIndex: 2,
  },
  {
    id: "w8",
    text: "Duck",
    phonics: "/d\u028ck/",
    meaning: "\u9e2d\u5b50",
    illustration: "A yellow duck swimming in a pond",
    options: ["Duck", "Swan", "Goose", "Hen"],
    correctIndex: 0,
  },
  {
    id: "w9",
    text: "Bear",
    phonics: "/ber/",
    meaning: "\u718a",
    illustration: "A friendly brown bear holding a honey pot",
    options: ["Wolf", "Fox", "Deer", "Bear"],
    correctIndex: 3,
  },
  {
    id: "w10",
    text: "Turtle",
    phonics: "/\u02c8t\u025c\u02d0rtl/",
    meaning: "\u4e4c\u9f9f",
    illustration: "A small turtle walking on sand",
    options: ["Turtle", "Snail", "Lizard", "Crab"],
    correctIndex: 0,
  },
];

export const dailyTasks: DailyTask[] = [
  {
    id: "t1",
    title: "Listen & Learn",
    description: "Listen to 3 new words",
    icon: "headphones",
    completed: true,
  },
  {
    id: "t2",
    title: "Say It Out Loud",
    description: "Practice speaking 2 words",
    icon: "mic",
    completed: false,
  },
  {
    id: "t3",
    title: "Write & Draw",
    description: "Trace 1 new word",
    icon: "pencil",
    completed: false,
  },
];

export const streakDays = 7;
export const totalStars = 23;
