Feature: AI picture book
  As a learner
  I want to open a sample picture book generated by the mascot
  So that reviewing words feels like reading a story

  Scenario: A new user opens a sample picture book and sees its title and pages
    Given I am logged in as a new user
    Then I should see the picture book section
    When I click the view sample book button
    Then I should see the picture book modal with a non-empty title and at least one page with non-empty text
